version: "3.8"

services:
  rgrback:
    image: rgrback:latest
    ports:
      - "8081:8081"
    networks:
      - my-network

  rgrfront:
    image: rgrfront:latest
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://rgr-back:8081
    networks:
      - my-network

networks:
  my-network:
